/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IZKAFactory__factory } from "./IZKAFactory__factory";
export { IZKAVerifier__factory } from "./IZKAVerifier__factory";
