/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZKAVerifier,
  IZKAVerifierInterface,
} from "../../../contracts/interface/IZKAVerifier";

const _abi = [
  {
    inputs: [],
    name: "ZKAFactory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ZKVerifier",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
    ],
    name: "fetchProofKey",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_ZKAFactory",
        type: "address",
      },
      {
        internalType: "address",
        name: "_ZKVerifier",
        type: "address",
      },
    ],
    name: "initializer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "zkProof",
        type: "bytes",
      },
    ],
    name: "zkpVerify",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IZKAVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IZKAVerifierInterface {
    return new Interface(_abi) as IZKAVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZKAVerifier {
    return new Contract(address, _abi, runner) as unknown as IZKAVerifier;
  }
}
