/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  VerifierMock,
  VerifierMockInterface,
} from "../../../contracts/mock/VerifierMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060ce8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80638e760afe14602d575b600080fd5b604060383660046054565b600192915050565b604051901515815260200160405180910390f35b60008060208385031215606657600080fd5b823567ffffffffffffffff80821115607d57600080fd5b818501915085601f830112609057600080fd5b813581811115609e57600080fd5b86602082850101111560af57600080fd5b6020929092019691955090935050505056fea164736f6c6343000817000a";

type VerifierMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VerifierMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VerifierMock__factory extends ContractFactory {
  constructor(...args: VerifierMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      VerifierMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): VerifierMock__factory {
    return super.connect(runner) as VerifierMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VerifierMockInterface {
    return new Interface(_abi) as VerifierMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VerifierMock {
    return new Contract(address, _abi, runner) as unknown as VerifierMock;
  }
}
