/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
import type * as mock from "./mock";
export type { mock };
export type { SPVVerifier } from "./SPVVerifier";
export type { ZKAFactory } from "./ZKAFactory";
export type { ZKAVerifier } from "./ZKAVerifier";
